package ebpf

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"log"
	"net"

	"github.com/jrroman/caza/pkg/metrics"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/prometheus/client_golang/prometheus"
)

// $BPF_CLANG and $BPF_CFLAGS are set by the Makefile.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc $BPF_CLANG -cflags $BPF_CFLAGS -type event bpf fentry.c -- -I./headers

// We need to read the events being sent from our fentry.c program via ringbuffer.
// These events occur on tcp_close events and contain the src and dest ip and port.
func readLoop(ctx context.Context, rd *ringbuf.Reader, ec chan bpfEvent) {
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	// bpfEvent is generated by bpf2go.
	var event bpfEvent
	for {
		record, err := rd.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				log.Println("received signal, exiting..")
				return
			}
			log.Printf("reading from reader: %s", err)
			continue
		}

		// Parse the ringbuf event entry into a bpfEvent structure.
		if err := binary.Read(bytes.NewBuffer(record.RawSample), NativeEndian, &event); err != nil {
			log.Printf("parsing ringbuf event: %s", err)
			continue
		}
		ec <- event
	}
}

// We need to process the events being sent down the event channel. As a first stab
// lets create an IP map it could look something like map[net.IP]struct{in out}
func processEvents(ctx context.Context, ec chan bpfEvent, networks map[string]*net.IPNet) {
	log.Printf("%-15s %-6s -> %-15s %-6s",
		"Src addr",
		"Port",
		"Dest addr",
		"Port",
	)
	for event := range ec {
		srcAddr, dstAddr := intToIP(event.Saddr), intToIP(event.Daddr)
		srcPort, dstPort := event.Sport, event.Dport
		for name, network := range networks {
			labels := prometheus.Labels{"network": name}
			// Identify where the srcAddr originates
			if network.Contains(srcAddr) {
				// check if the destination is in the same network
				if network.Contains(dstAddr) {
					metrics.InNetwork.With(labels).Inc()
					log.Printf("in network %-15s %-6d -> %-15s %-6d",
						srcAddr, srcPort, dstAddr, dstPort)
					continue
				}
				metrics.OutNetwork.With(labels).Inc()
				log.Printf("out network %-15s %-6d -> %-15s %-6d",
					srcAddr, srcPort, dstAddr, dstPort)
			}
		}
	}
}

func Run(ctx context.Context) {
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	// Allow current process to lock memory for eBPF resources
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Printf("Remove memory lock: %v", err)
		return
	}

	// Load pre-compiled programs and maps into the kernel
	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Printf("Load BPF objects: %v", err)
		return
	}
	defer objs.Close()

	link, err := link.AttachTracing(link.TracingOptions{
		Program: objs.bpfPrograms.TcpClose,
	})
	if err != nil {
		log.Printf("Attach link tracing: %v", err)
		return
	}
	defer link.Close()

	/**
	Read new tcp events from the ring buffer event data structure
	struct event {
		u16 sport;
		u16 dport;
		u32 saddr;
		u32 daddr;
	}
	*/
	rd, err := ringbuf.NewReader(objs.bpfMaps.Events)
	if err != nil {
		log.Printf("Ringbuf new reader: %v", err)
		return
	}
	defer rd.Close()

	networks, err := createNetworkMap()
	if err != nil {
		log.Printf("Create network map: %v", err)
		return
	}

	eventChan := make(chan bpfEvent)
	go readLoop(ctx, rd, eventChan)
	processEvents(ctx, eventChan, networks)
}
